### ISSUE TITLE
Unable to download pretrained models

### ISSUE THREAD

**Issue by GuidoBartoli** [pkorus/jpeg-mbfdf-forensics#2]
Hi, I tried to download the pre-trained models following the [link](http://kt.agh.edu.pl/~korus/files/mbfdf_pretrained_svm_models_20_modes_mat.tar.gz) in the README, but it seems to not exist anymore.
Is it still accessible from another link?

Many thanks

**Comment by pkorus** [comment]
Hi, Thanks for letting me know. I updated the link to [Google drive](https://drive.google.com/file/d/1aJjrM0TkgGkvJgN78Xotu9ZueZthjt7L/view?usp=sharing).
