### ISSUE TITLE
Unavailable article link

### ISSUE THREAD

**Issue by GuidoBartoli** [pkorus/jpeg-mbfdf-forensics#3]
Hi,
I would like to read the [article](http://dx.doi/10.1109/TIP.2016.2518870) mentioned in the README to gather information about the training procedure, but the link is not available anymore. Can you please provide a working link?

Many thanks!

**Comment by pkorus** [comment]
Hi, thanks for letting me know. I've updated the link: http://dx.doi.org/10.1109/TIP.2016.2518870

In case you're having problems accessing the PDF, you can also find pre-prints on [my website](http://pkorus.pl/publications)
